kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker:18
    settings:
      repo: leganck/python-web
      auto_tag_suffix: linux-amd64
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

