kind: pipeline
type: docker
name: default

platform:
  arch: amd64
  os: linux

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: leganck/python-web
      auto_tag_suffix: linux-amd64
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: deploy
    image: danielgormly/drone-plugin-kube
    settings:
      namespace: drone
      template: deployment.yml
      ca: 
        from_secret: k8s_cert
      server: 
        from_secret: k8s_server
      token:
        from_secret: k8s_token
