kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: leganck/python-web
      auto_tag_suffix: linux-amd64
      auto_tag: true
      username: leganck
      password:
        from_secret: Aallq123

