apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-web
  namespace: drone
spec:
  selector:
    matchLabels:
      app: python-web
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-web
        image: python-web:0.0.1-linux-amd64
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

