apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web
  namespace: drone
spec:
  selector:
    matchLabels:
      app: python-web
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-web
        image: leganck/python-web:linux-amd64
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 5000

